login: &login
  adapter: postgresql
  username: postgres
  password: postgres
  encoding: utf8

development:
  <<: *login
  database: roomscheduler_dev

test:
  <<: *login
  database: roomscheduler_test


production:
  adapter: postgresql
  database: roomscheduler
  pool: 5
  timeout: 5000
